khadas/fenix

config/functions/build
config/functions/build: 第 8 行:[: 缺少 `]'
Signed-off-by: ykdl <832666+zhangn1985@users.noreply.github.com>
=> fix a mistake

packages/u-boot-mainline/package.mk
due to below error in docker:
fip/acs_tool.pyc: line 1: $'\003\363\r': command not found
fip/acs_tool.pyc: line 2: $'\373]\372Uc\a@s*\002dd\001lZdd\001l\001Z\001dd\001l\002Z\001dd\001l\003Z\003dd\002l\004Tdd\001l\005Z\005dd\001l\006Z\006dd\001l\aZ\add\001l\bZ\bd\003Z': command not found
: No such file or directorye
fip/acs_tool.pyc: line 4: d
d                          e
: No such file or directory
fip/acs_tool.pyc: line 11: unexpected EOF while looking for matching ``'
fip/acs_tool.pyc: line 41: syntax error: unexpected end of file
Makefile:7: recipe for target 'all' failed
make: *** [all] Error 2
this requires to use python to run .pyc
Signed-off-by: Zhang Ning <832666+zhangn1985@users.noreply.github.com>
=> use python to run .pyc

archives/filesystem/special/VIM-COMMON/usr/local/bin/fan.sh
1) Corrected a bug that prevents to set the correct level after off
Enable must be the first command to be executed
2) Added a mode/level CLI parameter that allows someone to change the mode/level or use some policies/rules to change mode/level automatically
3) Messages are sent to syslog using logger
4) Kernel mode is not affected by this changes, because the parameter defaults to `boot` using the default behavior
```bash
khadas@Khadas:~$ sudo fan.sh usage
Error: Fan mode/level is unknown!
Usage: /usr/local/bin/fan.sh [on|low|mid|high|auto|off] - Set fan mode/level
/usr/local/bin/fan.sh [mode] - Query fan mode/level
Examp: /usr/local/bin/fan.sh auto
```
```bash
khadas@Khadas:~$ sudo fan.sh mode
Fan mode: auto
Fan level: off
```
=> Added command line parameter for mode/level changes in fan.sh

packages/linux-mainline/patches/5.7-rc7/0101-amlogic_vim_spifc_fix.patch, packages/linux-mainline/patches/5.7-rc7/0102-amlogic_vim2_vim3_led_fix.patch, packages/linux-mainline/patches/5.7-rc7/0103-rockchip_khadas_edge_add_missed_spiflash.patch, packages/linux-mainline/patches/5.7-rc7/0104-rockchip_khadas_edge_add_ir_recv.patch
4 files changed, 210 insertions(+)
create mode 100644 packages/linux-mainline/patches/5.7-rc7/0101-amlogic_vim_spifc_fix.patch
create mode 100644 packages/linux-mainline/patches/5.7-rc7/0102-amlogic_vim2_vim3_led_fix.patch
create mode 100644 packages/linux-mainline/patches/5.7-rc7/0103-rockchip_khadas_edge_add_missed_spiflash.patch
create mode 100644 packages/linux-mainline/patches/5.7-rc7/0104-rockchip_khadas_edge_add_ir_recv.patch
=> linux-mainline-patches

config/functions/common-functions
This is in reference to issue #106. If binfmt_misc is built into the host kernel, the module checks will fail, even though binfmt_misc can be used. But it still might need to be mounted first. So the checks here work like this:
- first check if there is a /proc mountpoint
- if not, try to mount it (which will work if binfmt_misc is built in)
- if it doesn't work, do the module checks (line 153 to 167)
This works on my machine with binfmt_misc built-in. If binfmt_misc is a module on the host system, the mount command will fail, and old code will be run (line 153 to 167) which should load the module etc. like before.
=> Rewrite check for built-in binfmt_misc

config/functions/common-functions
Running Fenix on a fresh, clean, minimal Debian install, results in an error because lsb_release is not installed by default. Also not all distros have lsb_release. However /etc/os-release is more standard, and available by default.
=> lsb_release is not installed by default; use /etc/os-release instead

config/config
I’ve been working on getting Fenix to run on Gentoo. /etc/timezone is a Debian-ism that Gentoo does not use, and I’d imagine other distros don’t have that either. On the other hand, /etc/localtime is used by the C library, so it’s much more common.
=> Resolve /etc/localtime as fallback for missing /etc/timezone

packages/linux-mainline/patches/5.17/0081-export-symbol-max_pcie_mrrs.patch, packages/linux-mainline/patches/5.17/0082-fix-amlogic-npu-build-issue.patch
Signed-off-by: Zhang Ning <832666+zhangn1985@users.noreply.github.com>
1, NPU驱动在out of source tree编译模式下，编译失败。
2, meson-pcie 驱动编译成模块的情况下，max_pcie_mrrs 找不到。
=> fix 2 build issues

Makefile, config/boards/VIM4.conf, config/bootscripts/extlinux/VIM4_extlinux_mainline.conf, config/functions/build, env/setenv.sh
Bunch of minor fixes
- Added new kernel-dtbs target to speed up execution of uboot-deb and uboot-image targets. As this only build kernel dtbs instead of the complete kernel, it saves a lot of time when doing uboot specific development and testing
- Reverted mainline kernel support for vim4. The mainline 6.4 kernel doesn't have vim4 dts or defconfig and does not build. Hence removing the same
- Also we ask to select u-boot version even when only single uboot version is available. So I have made the behavior consistent with Linux kernel selection where we automatically select the only available option
=> Minor fixes

config/functions/build-rootfs
On Ubuntu Lunar onwards, /etc/resolv.conf is a symlink to corresponding file in /run. As contents in /run doesn't persists at this point, the chroot-scripts fail to perform dns queries. This PR fixes the same.
=> Handle dns for symlinked resolv.conf files

config/boards/VIM1S.conf, config/boards/VIM3.inc, config/boards/VIM4.conf, config/functions/build-rootfs, packages/dracut_install/package.mk
This PR installs custom dracut install package that has [3de4c73](https://github.com/dracutdevs/dracut/commit/3de4c7313260fb600507c9b87f780390b874c870) and [131822e](https://github.com/dracutdevs/dracut/commit/131822e26d76a3ce2028e9a545be2af066805629) reverted.
Also we now only generate initrd once which also saves some time during the image build process.
PS: This PR depends on https://github.com/viraniac/dracut_install. It should be forked first before merging this PR.
=> dracut-install: fix performance regression

config/boards/Edge2.conf
Upstream packages seems to work fine on current mali-debs package
=> Edge2: jammy: remove self built mutter and xwayland packages

packages/rga-rockchip-debs/package.mk
=> packages: rga-rockchip-debs: update to 2.2.0

config/functions/build-board-deb
As I understood from Jacobe, this is no longer required and needs to be removed.
=> fix make debs failure when building debs for Edge2

archives/filesystem/special/Edge2/etc/wireplumber/main.lua.d/51-dmic.lua, archives/filesystem/special/Edge2/etc/wireplumber/main.lua.d/51-dp.lua, archives/filesystem/special/Edge2/etc/wireplumber/main.lua.d/51-es8316.lua, archives/filesystem/special/Edge2/etc/wireplumber/main.lua.d/51-hdmi.lua, config/config
Switched to pipewire instead of pulseaudio. Fixes video playback issue in the browser. 
Tested with 5.10 Noble image with sound playback on HDMI Audio and also on samsung galaxy buds bluetooth audio
=> Noble: remove pulseaudio to fix browser video playback issue

config/boards/VIM1S.conf, config/config
As chromium needs x11-utils, the creation of xfce image was broken. Also linux-gpu-mali-wayland package was getting installed which was causing the X server to fail, fixed the same as well.
=> Fixes for xfce image for vim1s

config/functions/build-rootfs
GNU Tar only seems to restore extended attributes that matches `user.*` pattern by default when --xattr pattern is used. Lets specifying that we want all extended attributes to be restored.
This fixes ping requiring sudo privileges. Now ping, arping, fping, etc in the image are keeping their cap_net_raw=ep capabilities as expected.
=> Fix missing capabilities resulting into ping not working for unprivileged users

config/boards/Edge2.conf, packages/gstreamer-rockchip-debs/package.mk
Encoding and decoding works on both 5.10 and 6.1 kernel on Noble. For jammy and bookworm, as older version of rga and mpp package is installed, mppvideodec and mpph264enc only works with 5.10 kernel.
Tested on jammy, bookworm and noble server images using following pipeline
```
$ gst-launch-1.0 filesrc location=~/Downloads/Big_Buck_Bunny_1080_10s_30MB.mp4 ! qtdemux name=d d.video_0 ! h264parse ! mppvideodec ! video/x-raw,format=NV12 ! mpph264enc ! h264parse ! mppvideodec ! video/x-raw,format=NV12 ! kmssink plane-id=101
```
Tested on Noble gnome image using following pipeline
```
$ gst-launch-1.0 filesrc location=~/Downloads/Big_Buck_Bunny_1080_10s_30MB.mp4 ! qtdemux name=d d.video_0 ! h264parse ! mppvideodec ! video/x-raw,format=NV12 ! mpph264enc ! h264parse ! mppvideodec ! …
```
=> Edge2: install custom gstreamer packages

config/config
When creating debian bookworm xfce image for VIM1S, I noticed the image still booted into gnome instead of xfce and it had both xfce and gnome installed on it. This fixes the same.
=> Fix: debian xfce images gets both gnome and xfce installed

config/boards/VIM3.conf, config/boards/VIM3L.conf
Depends on https://github.com/viraniac/khadas_linux/tree/khadas-linux-6.11.y
=> VIM3/3L: bump mainline to 6.11.2

config/functions/build-rootfs
Fix image build issue when building on docker desktop on Windows with WSL backend, partprobe fails with the following error
`
Error: Partition(s) 1, 2 on /dev/loop2 have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
`
Tested with docker desktop on Windows as well as docker desktop on MacOS using following command to create fenix container instance
```
$ docker run -it --name fenix --privileged \
--device=/dev/loop-control:/dev/loop-control \
--device=/dev/loop0:/dev/loop0 --cap-add SYS_ADMIN \
numbqq/fenix
```
=> Fix building on docker desktop for windows with WSL2 backend

config/boards/Edge2.conf, config/boards/VIM1S.conf, config/boards/VIM3.inc, config/boards/VIM4.conf
The panfrost/panthor support is disabled by default in dtb and dt overlays are needed to be applied during boot to use the same. Make sure they get listed in the overlay.env file when building images with panfrost support
=> Load panfrost/panthor-gpu overlay when building with PANFROST_SUPPORT

archives/filesystem/special/VIM-COMMON/usr/local/bin/hdmitx_hpd_event.sh
Generalize handling of display managers on hpd event for vim boards. Now if display-manager supports reload action, then the same is used otherwise they will get restarted on hotplug. As gdm supports reloading the service, this fixes application getting killed after sleep issue on Gnome image for vim boards. The xfce image for vim1s however will still have the same issue as lightdm still gets restarted on HDMI hotplug.
=> Generalize handling of display managers on hpd event

packages/rkbin/package.mk
Merge master fork
commit 9ab19cc4adfad92d415e0660ae95c60eac45c2eb
Author: Weiwen Chen <cww@rock-chips.com>
Date:   Wed Aug 27 14:25:44 2025 +0800
RKBOOT: Add RV1126BPMINIALL_FASTBOOT.ini
Signed-off-by: Weiwen Chen <cww@rock-chips.com>
Change-Id: I18ccffcef9e1b7002d32eb53b3fba68f673e653b
=> packages: rkbin: bump to 9ab19cc4

env/setenv.sh
It is totally cosmetic but `setenv.sh` uses `choose` incorrectly in some places where the correct word would be `choice`.
=> env: fix wording typo
