khadas/fenix

scripts/build.sh

build more debs, not only linux
Signed-off-by: ykdl <832666+zhangn1985@users.noreply.github.com>

update build target linux-deb

---

config/config
config/functions/common-functions

Signed-off-by: Zhang Ning <832666+zhangn1985@users.noreply.github.com>

allow override defualt apt mirror

---

config/boards/Edge.conf

build and install libmpp to edge debian builds

add libmpp to edge debian builds

---

config/boards/Edge.conf

Signed-off-by: frank <frank@khadas.com>

fixup! add mpp to edge debian builds

---

packages/u-boot-mainline/patches/2020.01-rc5/0013-script_replacement_for_source.patch
packages/u-boot-mainline/patches/2020.01-rc5/0015-uboot_env_emmc_fat_part.patch
packages/u-boot-mainline/patches/2020.01-rc5/0018-common_board_init_add_new_sub.patch
packages/u-boot-mainline/patches/2020.01-rc5/0018-meson_board_init_changes.patch
packages/u-boot-mainline/patches/2020.01-rc5/0019-env_fat_auto_detect_source.patch
packages/u-boot-mainline/patches/2020.01-rc5/0020-env_save_default_to_fat.patch

+ uboot mainline script replacement for source and cfgload
+ uboot mainline improve env uboot - store to fat partition auto create and save default state auto detect location

u-boot-mainline_script_and_env

---

config/config
config/functions/build-board-deb
config/functions/build-rootfs
config/functions/common-functions
env/setenv.sh
scripts/xze

hi
this patches add initial support for debian buster build

debian_buster_initial

---

config/functions/common-functions
scripts/xze

improve xz compression

---

packages/u-boot-mainline/patches/caad316b3165615f1a4848901811a4a084444c9d/0015-add-script-cmd-similar-with-source-or-autoscr-and-cf.patch
packages/u-boot-mainline/patches/caad316b3165615f1a4848901811a4a084444c9d/0021-add_autoscr_alias_for_script.patch

fixup with mainlinu uboot can't start kernel

---

packages/u-boot-mainline/patches/caad316b3165615f1a4848901811a4a084444c9d/0060-Autoboot-message-Hit-SPACE-in-d-seconds-to-stop-auto.patch

Autoboot message ; Hit SPACE in %d seconds to stop autoboot

---

.github/workflows/01.test_example.yml
.gitignore
Makefile
config/boards/Edge.conf
config/boards/VIM.inc
config/boards/VIM2.conf
config/config
config/etc/wgetrc_minimal_progress
config/functions/build
config/functions/build-board-deb
config/functions/build-rootfs
config/functions/common-functions
config/functions/git-repo
scripts/clean.sh
scripts/create_image.sh
scripts/rootfs_stage.sh
scripts/tests/build_test
scripts/tests/check_test
scripts/tests/signal_test
scripts/tests/upload
scripts/xze

improves for build fenix 

---

packages/linux-mainline/patches/5.14/0041-Add-text_offset.patch

Mainline linux: Fix typos

---

packages/linux-mainline/patches/5.14/0034-ETH-setup-mac-address-from-command-line.patch

Linux mainline: fixup the error assignment error with mac address

---

config/bootenv/VIM3L_env_ext.txt
config/bootenv/VIM3_env_ext.txt

Add can deices to VIM3 overlays option

---

Makefile

Consolidate all env checks for the various make targets, to reduce code duplication.

Deduplicate env validation in Makefile

---

config/functions/build-updater-deb

Signed-off-by: Frank Wang <frank@khadas.com>
Change-Id: Id0deddebab9ed9e86fc4e0365919ecb0cfdc7278

VIM3: remove tengine-libs form update deb

---

archives/hwpacks/wlan-firmware/brcm/config_bcm43438a1.txt
archives/hwpacks/wlan-firmware/brcm/config_bcm43456c5_ag.txt
archives/hwpacks/wlan-firmware/brcm/config_bcm4359c0_ag.txt
archives/hwpacks/wlan-firmware/brcm/config_bcm43752a2_ag.txt
archives/hwpacks/wlan-firmware/brcm/config_bcm43752a2_pcie_ag.txt

Signed-off-by: Ivan Li <ivan.li@wesion.com>

archives: wlan-firmware: add config file for wifi

---

config/boards/Edge1.conf
config/boards/VIM.inc
config/boards/VIM1.conf
config/boards/VIM2.conf
config/boards/VIM3.conf
config/boards/VIM3L.conf
config/functions/build

Signed-off-by: Frank Wang <frank@khadas.com>
Change-Id: I3dd14dfcc9edac6013b50eaaf5ab16e51623e111

change mainline kernel compile method

---

archives/filesystem/special/VIM1S/etc/modules

Solve the problem of Docker installation failure
Signed-off-by: Ivan.li <ivan.li@wesion.com>

VIM1S: Add loading module

---

config/boards/VIM1.conf
config/boards/VIM2.conf
config/boards/VIM3.conf
config/boards/VIM3L.conf

Signed-off-by: Frank Wang <frank@khadas.com>
Change-Id: I5f28c24c098cd10046f40ca614d3746badd2b977

linux-mainline: VIMs: update to linux 6.1

---

config/boards/VIM1.conf
config/boards/VIM2.conf
config/boards/VIM3.conf
config/boards/VIM3L.conf

Change-Id: Ic4b32ac85e4cfe5b72ff25a8fbf5d86eeebd5428

linux-mainline: update to kernel 6.2

---

archives/filesystem/special/VIM-COMMON/usr/local/bin/tone2.sh

Change-Id: Ia94a61bda6fdd6380b290622224d57ba250b231e

VIMs: fix tone2 application

---

config/config

On noble, there are some icons and cursors missing. From the login screen itself, we can see a square box instead of cursor pointer. This PR fixes the same.

Fix missing icons and cursors on noble

---

config/config
config/functions/build-common-deb
packages/fenix-config/package.mk

Depends on 
- https://github.com/viraniac/fenix-config
- https://github.com/khadas/linux/pull/129
- https://github.com/khadas/linux/pull/130

Add fenix-config

---

packages/rkbin/package.mk

Merge rockchip rkbin tag: linux-6.1-stan-rkr3

packages: rkbin: bump to 31cb9729

---

packages/fenix-config/package.mk

Source code for configng based fenix-config - https://github.com/viraniac/fenix-config/tree/configng

migrate to configng based fenix-config

---

packages/fenix-config/package.mk

depends on https://github.com/numbqq/fenix-config/pull/1

fenix-config: fix exit when user denies on prompt

---

archives/filesystem/special/VIM-COMMON/usr/local/bin/fan_setup.sh
archives/filesystem/special/VIM-COMMON/usr/local/bin/tone2.sh

adjust window size and unset WAYLAND_DISPLAY to use software rendering

VIMS: update fan_setup.sh and tone2.sh scripts

---

config/boards/Edge2.conf
packages/ffmpeg-debs/package.mk

ffmpeg repo - https://github.com/[viraniac/ffmpeg-debs](https://github.com/viraniac/ffmpeg-debs)

install custom ffmpeg package for rockchip
